FROM golang:1.13-alpine as build

WORKDIR $GOPATH/github.com/bitmark-inc/data-store

ADD go.mod .

RUN go mod download

ADD . .

RUN go install github.com/bitmark-inc/data-store/commands/cds


# ---

FROM alpine:3.10.3
ARG dist=0.0
COPY --from=build /go/bin/cds /

CMD ["/cds"]
